name: Push to production
on: [workflow_dispatch]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: push
        run: |
          git checkout -b production
          git push origin production -f