name: Push to production
on: [workflow_dispatch]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: push
        run: |
          git push origin production --force